# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2d7c72582d2590f74968531f02190574728d404305040a3e3202054c6beef27b559e9a813527333db2ef7220b7edd25c9027c63cd977bc6d3157b64aa0ba7943

test:
  secret_key_base: 4874bc2b57290feeca0d9f1dc7b1983b4f9068af89f2fda8e4649466abae138796771e995247b99279dd78749b128a4cfd66836475b1cc9df46474955f8cddb3

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
